language: android

android:
 components:
 - build-tools-27.0.3
 - android-26
 - android-22
 - add-on
 - extra
 - platform-tools
 - tools
 - extra-google-googleplayservices
 - extra-google-m2repository
 - extra-android-m2repository
 - addon-google_apis-google-19
 - sys-img-armeabi-v7a-android-22

before_install:
 - yes | sdkmanager "platforms;android-26"

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
  tags: true

env:
 global:
 - MALLOC_ARENA_MAX=2

sudo: required
script: ./gradlew :app:build
before_script:
 - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a -s "768x1280"
 - emulator -avd test -no-skin -no-audio -no-window &
 - adb wait-for-device
 - adb shell input keyevent 82 &