/*
 * Bandsintown API
 * # What is the Bandsintown API? The Bandsintown API is designed for enterprise partners and artists with websites, media players, and/or mobile applications that would like to list an artist's events and provide their users with the ability to buy tickets and RSVP to these events.  It offers read-only access to artist info and artist events: - artist info: returns the link to the Bandsintown artist page, the link to the artist photo, the current number of trackers and more - artist events: returns the list of upcoming events including their date and time, venue name and location, ticket links, lineup, description and the link to the Bandsintown event page  Note you can also search for events on a given date or within a given date range, including past dates.  # Getting Started - In order to use the Bandsintown API, you must have written consent from Bandsintown Inc. Any other use of the Bandsintown API is prohibited. [Contact Bandsintown](http://help.bandsintown.com/) to tell us what you plan to do and request your personal application ID. - Find out about the API methods available and the format of the API responses below. Select the method you wish to use and try it out online with the app ID provided to you. - Call our Bandsintown API with the app ID provided straight from your website or back-end platform and choose which element of the API response you wish to display. Scroll to the bottom of this page to find out about the Models used. 
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package enekes.abel.musicevents.network.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * ArtistData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-05T20:59:23.263+02:00")
public class ArtistData {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("image_url")
  private String imageUrl = null;

  @SerializedName("thumb_url")
  private String thumbUrl = null;

  @SerializedName("facebook_page_url")
  private String facebookPageUrl = null;

  @SerializedName("mbid")
  private String mbid = null;

  @SerializedName("tracker_count")
  private Integer trackerCount = null;

  @SerializedName("upcoming_event_count")
  private Integer upcomingEventCount = null;

  public ArtistData id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "510", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public ArtistData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "Maroon 5", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ArtistData url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(example = "http://www.bandsintown.com/Maroon5?came_from=67", required = true, value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ArtistData imageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * Get imageUrl
   * @return imageUrl
  **/
  @ApiModelProperty(example = "https://s3.amazonaws.com/bit-photos/large/7481529.jpeg", required = true, value = "")
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public ArtistData thumbUrl(String thumbUrl) {
    this.thumbUrl = thumbUrl;
    return this;
  }

   /**
   * Get thumbUrl
   * @return thumbUrl
  **/
  @ApiModelProperty(example = "https://s3.amazonaws.com/bit-photos/thumb/7481529.jpeg", required = true, value = "")
  public String getThumbUrl() {
    return thumbUrl;
  }

  public void setThumbUrl(String thumbUrl) {
    this.thumbUrl = thumbUrl;
  }

  public ArtistData facebookPageUrl(String facebookPageUrl) {
    this.facebookPageUrl = facebookPageUrl;
    return this;
  }

   /**
   * Get facebookPageUrl
   * @return facebookPageUrl
  **/
  @ApiModelProperty(example = "https://www.facebook.com/maroon5", required = true, value = "")
  public String getFacebookPageUrl() {
    return facebookPageUrl;
  }

  public void setFacebookPageUrl(String facebookPageUrl) {
    this.facebookPageUrl = facebookPageUrl;
  }

  public ArtistData mbid(String mbid) {
    this.mbid = mbid;
    return this;
  }

   /**
   * Get mbid
   * @return mbid
  **/
  @ApiModelProperty(example = "0ab49580-c84f-44d4-875f-d83760ea2cfe", required = true, value = "")
  public String getMbid() {
    return mbid;
  }

  public void setMbid(String mbid) {
    this.mbid = mbid;
  }

  public ArtistData trackerCount(Integer trackerCount) {
    this.trackerCount = trackerCount;
    return this;
  }

   /**
   * Get trackerCount
   * @return trackerCount
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getTrackerCount() {
    return trackerCount;
  }

  public void setTrackerCount(Integer trackerCount) {
    this.trackerCount = trackerCount;
  }

  public ArtistData upcomingEventCount(Integer upcomingEventCount) {
    this.upcomingEventCount = upcomingEventCount;
    return this;
  }

   /**
   * Get upcomingEventCount
   * @return upcomingEventCount
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getUpcomingEventCount() {
    return upcomingEventCount;
  }

  public void setUpcomingEventCount(Integer upcomingEventCount) {
    this.upcomingEventCount = upcomingEventCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtistData artistData = (ArtistData) o;
    return Objects.equals(this.id, artistData.id) &&
        Objects.equals(this.name, artistData.name) &&
        Objects.equals(this.url, artistData.url) &&
        Objects.equals(this.imageUrl, artistData.imageUrl) &&
        Objects.equals(this.thumbUrl, artistData.thumbUrl) &&
        Objects.equals(this.facebookPageUrl, artistData.facebookPageUrl) &&
        Objects.equals(this.mbid, artistData.mbid) &&
        Objects.equals(this.trackerCount, artistData.trackerCount) &&
        Objects.equals(this.upcomingEventCount, artistData.upcomingEventCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, url, imageUrl, thumbUrl, facebookPageUrl, mbid, trackerCount, upcomingEventCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtistData {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    thumbUrl: ").append(toIndentedString(thumbUrl)).append("\n");
    sb.append("    facebookPageUrl: ").append(toIndentedString(facebookPageUrl)).append("\n");
    sb.append("    mbid: ").append(toIndentedString(mbid)).append("\n");
    sb.append("    trackerCount: ").append(toIndentedString(trackerCount)).append("\n");
    sb.append("    upcomingEventCount: ").append(toIndentedString(upcomingEventCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

